# Generated by Django 5.1.6 on 2025-03-07 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumno',
            options={'managed': False},
        ),
    ]
