# Generated by Django 5.1.6 on 2025-03-08 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_alumno_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='alumno',
            table='database"."alumnos',
        ),
    ]
