# Generated by Django 5.1.7 on 2025-03-16 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_alumno_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='alumno',
            table='alumnos',
        ),
    ]
